sudo: required
language: generic
services:
    - docker

before_install:
    - docker build -t rafesaunders/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true rafe/saunders/docker-react npm run test
    
